version: '3.8'

services:
  web-monitor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=file
      - GLOBAL_WEBHOOK_URL=https://exemplo.com/webhook
    volumes:
      - ./config:/app/config
      - ./data:/app/data