service: hootfy

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 240
  environment:
    TZ: America/Sao_Paulo
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:ListBucket"
        - "s3:GetObject"
      Resource: 
        - "arn:aws:s3:::hivecloud-backup"
        - "arn:aws:s3:::hivecloud-backup/*"

functions:
  check:
    handler: src/lambda/lambda-handler.check 
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:50 
      - arn:aws:lambda:us-east-1:462728573761:layer:sharp:2
    events:
      - schedule:
          rate: cron(0 11,17 * * ? *) # Executa às 08:00 e 14:00