service: hootfy

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 240
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::hivecloud-backup/*"

functions:
  check:
    handler: src/lambda/lambda-handler.check 
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:50 
      - arn:aws:lambda:us-east-1:462728573761:layer:sharp:2
    events:
      - schedule:
          rate: cron(0 8,14 * * ? *) # Executa às 08:00 e 14:00